# BDCraft Configuration File

# Plugin settings
plugin:
  # Whether debug mode is enabled
  debug: false
  # Whether to block competing plugins
  block-competing-plugins: true

# Economy settings
economy:
  # Currency settings
  currency:
    # The name of the currency
    name: "BD Coin"
    # The plural name of the currency
    plural: "BD Coins"
    # The symbol used for the currency
    symbol: "§6BD§r"
  # Market settings
  market:
    # The radius of markets by level
    radius:
      1: 32
      2: 48
      3: 64
      4: 80
    # Maximum number of collectors by level
    max-collectors:
      1: 3
      2: 5
      3: 7
      4: 10
    # The price multiplier for markets by level
    price-multiplier:
      1: 1.0
      2: 1.05
      3: 1.10
      4: 1.15

# Progression settings
progression:
  # Experience required for each rank
  rank-experience:
    # Newcomer to Farmer
    1: 1000
    # Farmer to Expert Farmer
    2: 5000
    # Expert Farmer to Master Farmer
    3: 15000
    # Master Farmer to Agricultural Expert
    4: 50000
  # Rebirth requirements
  rebirth:
    # Whether rebirth is enabled
    enabled: true
    # Currency required for rebirth
    currency-requirement: 100000
    # Number of trades required for rebirth
    trades-requirement: 500
    # Minimum rank required for rebirth
    rank-requirement: 5
    # Experience multiplier per rebirth level
    experience-multiplier: 0.1
    # Crop yield multiplier per rebirth level
    crop-yield-multiplier: 0.05
    # Trade value multiplier per rebirth level
    trade-value-multiplier: 0.08
    # Maximum rebirth level
    max-rebirth-level: 10

# Display settings
display:
  # Scoreboard settings
  scoreboard:
    # Whether the scoreboard is enabled
    enabled: true
    # The title of the scoreboard
    title: "&6&lBD Economy"
    # The update interval in ticks (20 ticks = 1 second)
    update-interval: 100
    # Whether the scoreboard is enabled by default for new players
    default-enabled: true

# Trading settings
trading:
  # Collector settings
  collector:
    # The regular collector crop requirements and rewards
    regular:
      # Number of crops required
      crops: 10
      # Number of emeralds rewarded
      emeralds: 2
      # Amount of BD currency rewarded
      currency: 50
    # The green collector crop requirements and rewards
    green:
      # Number of crops required
      crops: 5
      # Number of emeralds rewarded
      emeralds: 10
      # Amount of BD currency rewarded
      currency: 150
    # The purple collector crop requirements and rewards
    purple:
      # Number of crops required
      crops: 3
      # Number of emeralds rewarded
      emeralds: 20
      # Amount of BD currency rewarded
      currency: 400