# BDCraft Plugin Configuration
# Complete configuration file for the BDCraft plugin system

# General plugin settings
plugin:
  debug: false
  prefix: '&7[&aBDCraft&7]'
  language: 'en'
  data-storage: 'file' # 'file', 'mysql', 'sqlite'

# Module enabling/disabling
modules:
  # Core module management
  logging: true
  economy: true
  permissions: true
  vital: true
  placeholder: true

# Logging module configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console-output: true
  file-output: true
  max-memory-logs: 1000
  categories:
    - economy
    - permissions
    - vital
    - commands
    - players
  
# Economy module configuration  
economy:
  # Credits (server currency) configuration
  # Note: Emeralds are handled as physical items by the game
  # Credits are earned exclusively by trading with collectors (no starting balance)
  credits-enabled: true
  transaction-log: true
  max-transaction-history: 50
  
# Permissions module configuration
permissions:
  use-bukkit-perms: true
  default-group: 'player'
  permission-caching: true
  cache-duration: 60
  clear-on-join: true
  
# Vital module configuration
vital:
  # Home system limits based on ranks
  max-homes:
    # As per documentation
    rank1: 1  # Newcomer
    rank2: 2  # Farmer
    rank3: 3  # Expert Farmer
    rank4: 4  # Master Farmer
    rank5: 5  # Agricultural Expert
  
  # Teleportation cooldowns in seconds
  teleport:
    cooldown: 30
    expire: 30
    back-enabled: true
    back-cooldown: 60
  
  # Market warps based on market level
  market-warps:
    level1: false          # No public warp
    level2-cooldown: 3600  # 1 hour cooldown
    level3-cooldown: 1800  # 30 minute cooldown
    level4-cooldown: 900   # 15 minute cooldown
  
  # Protection system
  protection:
    pvp-in-markets: false
    log-interactions: true
    rollback-enabled: true

# Data storage configuration
storage:
  # MySQL configuration (if data-storage is 'mysql')
  mysql:
    host: 'localhost'
    port: 3306
    database: 'bdcraft'
    username: 'user'
    password: 'password'
    prefix: 'bd_'
    
  # SQLite configuration (if data-storage is 'sqlite')
  sqlite:
    file: 'database.db'
    
# Version of this config file. Do not change this!
config-version: 1
