# BDCraft Main Configuration
# This file controls general plugin settings

# Plugin settings
plugin:
  # Debug mode (enables additional logging)
  debug: false
  # Language file to use
  language: 'en'

# Module settings
modules:
  # Enable/disable modules
  economy: true
  perms: true
  vital: true

# Database settings
database:
  # Database type (sqlite, mysql)
  type: 'sqlite'
  
  # MySQL settings (only used if type is mysql)
  mysql:
    host: 'localhost'
    port: 3306
    database: 'bdcraft'
    username: 'root'
    password: 'password'
    useSSL: false
    
  # Connection pool settings
  pool:
    maxPoolSize: 10
    minIdle: 5
    maxLifetime: 1800000
    connectionTimeout: 5000

# Cache settings
cache:
  # Time in seconds before cached data expires
  expiry: 300
  # Maximum number of items to keep in memory caches
  maxSize: 1000