# BDCraft Core Configuration

# Plugin Settings
debug-mode: false
metrics-enabled: true
check-updates: true
update-notify: true
language: "en"

# Module Settings
modules:
  economy: true
  perms: true
  auction: true
  rebirth: true
  tutorial: true
  logging: true
  storage-mysql: false

# Player Markets
player-markets:
  enabled: true
  min-distance: 30
  market-radius: 49
  max-markets-per-player: 1
  max-collectors-initial: 3
  max-collectors-upgraded: 10
  market-visualize-time: 10
  display-particles: true
  reputation-decay:
    enabled: false
    rate: 1
    period: 7

# BD Seeds and Crops
growing:
  regular-growth-ticks: 4800
  green-growth-modifier: 0.7
  purple-growth-rate: 1.0
  particles-enabled: true
  growth-stage-notification: true
  bonemeal-allowed: false
  special-biome-bonuses: true
  biome-modifiers:
    PLAINS: 1.0
    FOREST: 1.2
    JUNGLE: 0.8
    DESERT: 1.3

# Market Upgrade Settings
market-upgrade-costs:
  level2:
    diamonds: 16
    currency: 5000
  level3:
    diamonds: 32
    currency: 10000
  level4:
    diamonds: 64
    currency: 25000
    
market-benefits:
  level2:
    price-bonus: 0.05
    collector-limit: 5
  level3:
    price-bonus: 0.10
    collector-limit: 7
    seasonal-trader: true
  level4:
    price-bonus: 0.15
    collector-limit: 10
    seasonal-trader: true
    player-buffs: true

# Plugin Integrations
integrations:
  vault: true
  placeholderapi: true
  worldguard: true
  worldedit: true
  coreprotect: true
  dynmap: true
  luckperms: true

# Database Configuration (if storage-mysql is true)
database:
  host: "localhost"
  port: 3306
  database: "bdcraft"
  username: "bdcraft"
  password: "password"
  prefix: "bd_"
  connection-pool: 3
  ssl: false

# Drop Rates
drop-rates:
  green-seed-from-regular: 0.05
  purple-seed-from-green: 0.01
  diamond-from-regular: 0.02