name: BDCraft
version: 1.0.0
main: com.bdcraft.plugin.BDCraft
api-version: '1.21'
author: BDCraft Team
description: A comprehensive economy and market system plugin for Minecraft
website: https://bdcraft.com

commands:
  bdscoreboard:
    description: Toggles the BDCraft scoreboard
    usage: /bdscoreboard [toggle|on|off|reload]
    aliases: [bdsc, bdboard]
    permission: bdcraft.scoreboard
  bdbalance:
    description: Checks your BD currency balance
    usage: /bdbalance
    aliases: [bdbal, bdmoney]
    permission: bdcraft.balance
  bdpay:
    description: Pay BD currency to another player
    usage: /bdpay <player> <amount>
    permission: bdcraft.pay
  bdmarket:
    description: Manage your markets
    usage: /bdmarket [create|list|info|upgrade|addassociate|removeassociate]
    aliases: [bdm, markets]
    permission: bdcraft.market
  bdrebirth:
    description: Rebirth to gain permanent bonuses
    usage: /bdrebirth
    permission: bdcraft.rebirth
  bdrank:
    description: Check your current rank
    usage: /bdrank
    permission: bdcraft.rank
  bdaura:
    description: Toggle your rebirth aura
    usage: /bdaura
    permission: bdcraft.rebirth.aura
  bdbless:
    description: Bless another player with temporary bonuses
    usage: /bdbless <player>
    permission: bdcraft.rebirth.bless
  bdtouch:
    description: Apply rebirth touch to crops
    usage: /bdtouch
    permission: bdcraft.rebirth.touch
  bdinsight:
    description: Get economic insights and predictions
    usage: /bdinsight [market|economy|trends]
    permission: bdcraft.insight
  bdadmin:
    description: Admin commands for BDCraft
    usage: /bdadmin [reload|setmoney|setrank|resetplayer|market]
    permission: bdcraft.admin

permissions:
  bdcraft.*:
    description: Gives access to all BDCraft commands
    children:
      bdcraft.scoreboard: true
      bdcraft.balance: true
      bdcraft.pay: true
      bdcraft.market: true
      bdcraft.rebirth: true
      bdcraft.rank: true
      bdcraft.insight: true
      bdcraft.admin: true
      bdcraft.rebirth.*: true
  bdcraft.scoreboard:
    description: Allows using scoreboard commands
    default: true
  bdcraft.balance:
    description: Allows checking balance
    default: true
  bdcraft.pay:
    description: Allows paying other players
    default: true
  bdcraft.market:
    description: Allows basic market usage
    default: true
  bdcraft.market.create:
    description: Allows creating markets
    default: true
  bdcraft.market.create.tier1:
    description: Allows creating up to 1 market
    default: true
  bdcraft.market.create.tier2:
    description: Allows creating up to 2 markets
    default: op
  bdcraft.market.create.tier3:
    description: Allows creating up to 3 markets
    default: op
  bdcraft.rebirth:
    description: Allows using rebirth
    default: true
  bdcraft.rebirth.*:
    description: Allows using all rebirth features
    children:
      bdcraft.rebirth.aura: true
      bdcraft.rebirth.bless: true
      bdcraft.rebirth.touch: true
  bdcraft.rebirth.aura:
    description: Allows using rebirth aura
    default: true
  bdcraft.rebirth.bless:
    description: Allows blessing other players
    default: true
  bdcraft.rebirth.touch:
    description: Allows using rebirth touch
    default: true
  bdcraft.rank:
    description: Allows checking rank
    default: true
  bdcraft.insight:
    description: Allows using economic insights
    default: true
  bdcraft.admin:
    description: Allows using admin commands
    default: op