name: BDCraft
version: '${version}'
main: com.bdcraft.plugin.BDCraft
api-version: '1.21'
authors: [BDCraft Team]
description: 'A comprehensive Minecraft server management plugin with farming-based economy, player markets with villager trading, and progression systems'
website: https://bdcraft.org

commands:
  bdcraft:
    description: Main command for BDCraft plugin
    usage: /bdcraft <subcommand> [args]
    aliases: [bd]
    permission: bdcraft.admin
  
  bdhelp:
    description: Shows help information for BDCraft commands
    usage: /bdhelp [command]
    aliases: [bdh]
    permission: bdcraft.help
  
  bdadmin:
    description: Administrative commands for BDCraft
    usage: /bdadmin <subcommand> [args]
    aliases: [bda]
    permission: bdcraft.admin
  
  # Economy Commands
  bdcurrency:
    description: Currency management commands
    usage: /bdcurrency <balance|pay|top> [args]
    aliases: [bdc]
    permission: bdcraft.currency
    
  # Market Commands
  bdmarket:
    description: Market management commands
    usage: /bdmarket <create|info|list|warp> [args]
    aliases: [bdm]
    permission: bdcraft.market
    
  # Rank Commands
  bdrank:
    description: Displays and manages player ranks
    usage: /bdrank [player] [set|info|list] [rank]
    aliases: [bdrk]
    permission: bdcraft.rank
    
  # Vital Module Commands
  bdtp:
    description: Request to teleport to a player
    usage: /bdtp <player>
    permission: bdvital.tp
    
  bdtpa:
    description: Accept a teleport request
    usage: /bdtpa
    permission: bdvital.tpa
    
  bdtpd:
    description: Deny a teleport request
    usage: /bdtpd
    permission: bdvital.tpa
    
  bdtpr:
    description: Request a player to teleport to you
    usage: /bdtpr <player>
    permission: bdvital.tpr
    
  bdback:
    description: Return to previous location or death point
    usage: /bdback
    permission: bdvital.back
    
  bdspawn:
    description: Teleport to server spawn
    usage: /bdspawn
    permission: bdvital.spawn
    
  bdhome:
    description: Home system commands
    usage: /bdhome [set|del|list] [name]
    permission: bdvital.home
    
  bdmsg:
    description: Send a private message
    usage: /bdmsg <player> <message>
    permission: bdvital.msg
    
  bdr:
    description: Reply to last private message
    usage: /bdr <message>
    permission: bdvital.msg
    
  bdmail:
    description: Mail system commands
    usage: /bdmail <send|read|clear> [player] [message]
    permission: bdvital.mail
    
  bddeathinfo:
    description: Show coordinates of last death
    usage: /bddeathinfo
    permission: bdvital.deathinfo
    
  # Rebirth Command
  bdrebirth:
    description: Manage player rebirth and prestige
    usage: /bdrebirth [check|confirm|stats] [player]
    aliases: [bdrb]
    permission: bdcraft.rebirth
    
  # Admin Commands
  bdgive:
    description: Gives BD items to players
    usage: /bdgive item <player> <item_id> [amount] [value]
    aliases: [bdg]
    permission: bdcraft.admin.give

permissions:
  # Admin Permissions
  bdcraft.admin:
    description: Gives access to administrative commands
    default: op
    children:
      bdcraft.admin.reload: true
      bdcraft.admin.status: true
      bdcraft.admin.economy: true
      bdcraft.admin.items: true
      bdcraft.admin.rank: true
      bdcraft.admin.rebirth: true
      bdcraft.admin.market: true
      bdcraft.admin.villager: true
      bdcraft.admin.debug: true
      
  # Economy Permissions
  bdcraft.currency:
    description: Allows currency commands
    default: true
    
  # Market Permissions
  bdcraft.market.create:
    description: Allows creating markets
    default: true
    
  bdcraft.market.check:
    description: Allows checking market boundaries
    default: true
    
  bdcraft.market.info:
    description: Allows viewing market info
    default: true
    
  # Rank Permissions
  bdcraft.rank.view:
    description: Allows viewing ranks
    default: true
    
  bdcraft.rank.up:
    description: Allows ranking up
    default: true
    
  # Rebirth Permissions
  bdcraft.rebirth:
    description: Allows accessing rebirth system
    default: true
    children:
      bdcraft.rebirth.check: true
      bdcraft.rebirth.confirm: true
      bdcraft.rebirth.stats: true
      
  bdcraft.rebirth.check:
    description: Allows checking rebirth eligibility
    default: true
    
  bdcraft.rebirth.confirm:
    description: Allows confirming rebirth
    default: true
    
  bdcraft.rebirth.stats:
    description: Allows viewing rebirth stats
    default: true
    
  bdcraft.rebirth.stats.others:
    description: Allows viewing other players' rebirth stats
    default: op
    
  # Deity Permissions (Rebirth 10)
  bdcraft.deity.bless:
    description: Allows using the bless command (Rebirth 10)
    default: false
    
  bdcraft.deity.predict:
    description: Allows predicting seasonal trader items (Rebirth 10)
    default: false
    
  bdcraft.deity.aura:
    description: Allows toggling abundance aura (Rebirth 10)
    default: false
    
  # Vital Module Permissions
  bdvital.tp:
    description: Allows teleporting to players
    default: true
    
  bdvital.tpa:
    description: Allows accepting/denying teleport requests
    default: true
    
  bdvital.tpr:
    description: Allows requesting players to teleport to you
    default: true
    
  bdvital.back:
    description: Allows returning to previous location
    default: true
    
  bdvital.spawn:
    description: Allows teleporting to spawn
    default: true
    
  bdvital.home:
    description: Allows using homes
    default: true
    
  bdvital.sethome:
    description: Allows setting homes
    default: true
    
  bdvital.msg:
    description: Allows private messaging
    default: true
    
  bdvital.mail:
    description: Allows using mail
    default: true
    
  bdvital.market.warp:
    description: Allows using market warps
    default: true
    
  bdvital.market.setwarp:
    description: Allows setting market warps
    default: false
    
  bdvital.deathinfo:
    description: Allows seeing death coordinates
    default: true